
#docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app fc5c8
FROM node:16-alpine

WORKDIR '/app'

COPY package.json .

RUN npm install
RUN npm config set unsafe-perm true

COPY . .

CMD ["npm","run","start"]